name: Jenkins Job Builder
description: Updates Jenkins Jobs
branding:
  icon: message-circle
  color: green

inputs:
  token:
    description: API token (https://www.jenkins.io/blog/2018/07/02/new-api-token-system/, preferred), or password
    required: true
  jobs_file:
    description: Path to YML file defining jobs
    required: false
    default: jobs.yml
  conf_file:
    description: Path to jenkins-job.ini file. Specify URL and username here. https://jenkins-job-builder.readthedocs.io/en/latest/execution.html
    required: false
    default: jenkins-jobs.ini

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        pip3 install -r "$GITHUB_ACTION_PATH/requirements.txt"
        $GITHUB_ACTION_PATH/gha.sh
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_JOBS_FILE: ${{ inputs.jobs_file }}
        INPUT_CONF_FILE: ${{ inputs.conf_file }}
